platform :ios, '12.1'
target 'WhereIsMyCup' do
pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end
